from typing import Literal, Protocol

COMPLEXITIES = Literal['both', 'time', 'space']


class SupportsComparison(Protocol):
    def __lt__(self, other: 'SupportsComparison') -> bool: ...
    def __le__(self, other: 'SupportsComparison') -> bool: ...
    def __gt__(self, other: 'SupportsComparison') -> bool: ...
    def __ge__(self, other: 'SupportsComparison') -> bool: ...
