site_name: AlgPy
nav:
  - Home: index.md
  - API:
      - Base:
          - Complexity Object: docs/api/complexity_object.rst
      - Algorithms:
          - Sorting:
              - Bubble Sort: docs/api/bubble_sort.rst
      - Data Structures:
          - Linear:
              - Linked List: docs/api/data_structures/linked_list.rst
      - Tools:
          - Random Input Generation: docs/api/tools/random_input_generation.rst
  - User Guide:
      - Algorithms:
          - Sorting:
              - Bubble Sort: docs/tutorials/sorting/bubble_sort.rst
theme: readthedocs
plugins:
  - search
  - mkdocstrings[python]